name: Build Lesspass Server

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/build-lesspass-server.yml'
      - 'build-lesspass-server.sh'
  workflow_dispatch:
    inputs:
      PUSH_CONTAINERS:
        description: 'push containers to aliyun'
        required: true
        default: 'true'
      UPLOAD_DIFF:
        description: 'uplode diff file'
        required: true
        default: 'false'
      UPLOAD_WED_DIRECTORY:
        description: 'uplode web directory'
        required: true
        default: 'false'
      SSH:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'
#  watch:
#    types: started

env:
  CONTAINER_URL: ${{ secrets.ALI_CONTAINER_URL_2 }}

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cloen lesspass source code
        run: git clone https://github.com/lesspass/lesspass.git

      - name: Load custom configuration
        env:
          CONTAINER_DOMAIN: ${{ secrets.ALI_CONTAINER_DOMAIN_2 }}
          CONTAINER_PATH: ${{ secrets.ALI_CONTAINER_PATH_2 }}
          DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL_2 }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST_2 }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER_2 }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD_2 }}
        run: |
          chmod +x build-lesspass-server.sh
          mv build-lesspass-server.sh lesspass/
          cd lesspass/
          ./build-lesspass-server.sh
          git diff >> "$GITHUB_WORKSPACE/diff.diff"
          echo "diff files md5:"
          md5sum "$GITHUB_WORKSPACE/diff.diff"

      - name: Upload diff file
        uses: actions/upload-artifact@v2
        if: github.event.inputs.UPLOAD_DIFF == 'true' && !cancelled()
        with:
          name: diff
          path: diff.diff

      - name: Start SSH via tmate
        uses: P3TERX/ssh2actions@main
        with:
          mode: ngrok
        if: github.event.inputs.SSH == 'true'
        env:
          # After sign up on the https://ngrok.com
          # You can find this token here: https://dashboard.ngrok.com/auth/your-authtoken
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          
          # ngrok server region [us, eu, au, ap, sa, jp, in] (optional, default: us)
          # You can find this server region here: https://ngrok.com/docs#global-locations
          NGROK_REGION: jp

          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.ALI_TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.ALI_TELEGRAM_CHAT_ID }}

      - name: Build containers
        run: |
          cd lesspass/containers/
          docker -v
          wget -q https://github.com/docker/compose/releases/download/1.28.5/docker-compose-Linux-x86_64 -O docker-compose
          chmod +x docker-compose
          ./docker-compose -v
          ./docker-compose build

      - name: Push containers
        if: github.event.inputs.PUSH_CONTAINERS == 'true' && !cancelled()
        env:
          ALI_LOGIN: ${{ secrets.ALI_DOCKER_REGISTRY_LOGIN_2 }}
        run: |
          docker images
          docker login $ALI_LOGIN
          docker tag $CONTAINER_URL/lesspass-frontend $CONTAINER_URL/lesspass-frontend:actions
          docker tag $CONTAINER_URL/lesspass-backend $CONTAINER_URL/lesspass-backend:actions
          docker push $CONTAINER_URL/lesspass-frontend:actions
          docker push $CONTAINER_URL/lesspass-backend:actions

      - name: Copy Wed Directory
        if: github.event.inputs.UPLOAD_WED_DIRECTORY == 'true' && !cancelled()
        run: |
          docker run -i -t -d $CONTAINER_URL/lesspass-frontend
          docker cp $(docker ps -q):/usr/share/nginx/html ./
          docker rm -f $(docker ps -q)

      - name: Upload Wed Directory
        if: github.event.inputs.UPLOAD_WED_DIRECTORY == 'true' && !cancelled()
        uses: actions/upload-artifact@v2
        with:
          name: webdir
          path: ./html/

      - name: Test containers
        run: |
          docker run -itd -p 45628:45628 $CONTAINER_URL/lesspass-backend
          docker run -itd -p 45629:45629 $CONTAINER_URL/lesspass-frontend
          sleep 20
          curl --connect-timeout 5 --retry 2 http://127.0.0.1:45628
          curl --connect-timeout 5 --retry 2 http://127.0.0.1:45629
          docker rm -f $(docker ps -q)
